Repository AtlassianPS/ConfluencePS, pull requests merged in 2018-05, with the labels that each got.

#136 Create CODE_OF_CONDUCT.md
  .github/CODE_OF_CONDUCT.md
Labels: Area:Documentation, Area:Module, Issue:Enhancement, Status:In Review

#137 Fix icon for CI
  README.md
Labels: Area:Repository, Issue:Bug, Status:In Review

#138 Updated Contributing & Getting Started URLs
  README.md
Labels: Area:Documentation, Issue:Bug, Status:In Review
